### ISSUE TITLE
Release with latest changes

### ISSUE THREAD

**Issue by postlund** [mockfs/mockfs#11]
Hi! I'm trying to use your library, however I'm having some issues with `open` as 1.1.2 does not have the `encoding` flag, which is implemented on `main`. Would it be possible to get a release on pypi with current changes to `main`?

**Comment by davvid** [comment]
Thanks for the heads-up.

https://pypi.org/project/mockfs/1.1.4/

**Comment by postlund** [comment]
Great, thanks! 👍
