### ISSUE TITLE
Update library on PyPI

### ISSUE THREAD

**Issue by alfateam123** [mockfs/mockfs#7]
The version on PyPI is older than the repository code and does not support Python 3, while the repository code _does_ support Py3.
Please, update the PyPI library. It's a nice library and it deserves some love.

Workaround (for library' client): in the meanwhile, put `git+http://github.com/mockfs/mockfs` into a `requirements.txt` file and use `pip -r requirements.txt` when installing your own libraries.

**Comment by davvid** [comment]
Thanks, pypi has been updated.

**Comment by alfateam123** [comment]
Thank you  (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧*:･ﾟ✧
